# Generated by Django 4.2.9 on 2024-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dhhfh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
